routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\User;
use App\Role;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Auth;

Route::get('/login', function () {
    return view('login');
});

Route::get('/', function () {
	$roles = explode(",", Auth::user()->roles);
	$role = Role::find($roles[0]);
	return redirect($role->url);
})->middleware('auth');

Route::get('/home', function () { return view('admission/registration'); })->middleware('auth');

Route::prefix('profile')->group(function () {
	Route::get('/', 'ProfileController@index')->middleware('auth')->name('profile');
	Route::get('edit', 'ProfileController@edit')->middleware('auth')->name('profile_edit');
	Route::post('update', 'ProfileController@update')->middleware('auth')->name('profile_update');
});

Route::prefix('admission')->group(function () {	
	Route::get('/', function () { return redirect('admission/registration'); });
	
    Route::resource('registration', 'RegistrationController', ['middleware' => 'auth']);

	Route::post('doctor_show_all', 'AdmissionController@doctorshowall');
	Route::post('doctor_list', 'AdmissionController@doctorlist');

    Route::post('reservation_ajax', 'AdmissionController@reservationajax')->middleware('auth');
    
	Route::resource('master_patient', 'PatientController', ['middleware' => 'auth']);
	Route::post('master_patient/ajaxdt', 'PatientController@ajaxdt')->middleware('auth')->name('master_patient_ajaxdt');
	Route::post('master_patient/search_by_name_dt', 'PatientController@searchbynamedt')->middleware('auth')->name('search_by_name_dt');
	
	Route::get('daily_patient', function () { return view('admission/daily-patient'); })->middleware('auth')->name('daily_patient');
	
	Route::get('doctor_schedule', 'DoctorRequestSessionController@index')->middleware('auth')->name('doctor_schedule');
	Route::post('doctor_schedule/request_session_leave', 'DoctorRequestSessionController@storeRequestSessionLeave')->middleware('auth')->name('request_session_leave');

	Route::get('doctor_late', 'DoctorLateController@index')->middleware('auth')->name('doctor_late');
	Route::post('doctor_late/request_late', 'DoctorLateController@storeRequestLate')->middleware('auth')->name('request_late');

	Route::get('doctor_leave', 'DoctorLeaveController@index')->middleware('auth')->name('doctor_leave');
	Route::post('doctor_leave/request_leave', 'DoctorLeaveController@storeRequestLeave')->middleware('auth')->name('request_leave');

	Route::get('program', function () { return view('admission/program'); })->middleware('auth')->name('program');
	
	Route::get('information', function () { return view('admission/information/index'); })->middleware('auth')->name('information');
	
	Route::post('doctor_search_by_code', 'AdmissionController@doctorsearchbycode')->middleware('auth')->name('doctor_search_by_code');
});

Route::prefix('self_checkin')->group(function () {
	Route::get('/', function() { return view('admission/self_checkin/booking'); } )->middleware('auth');
	Route::get('antrian_pharmacy', function() { return view('admission/self_checkin/antrian_pharmacy'); } )->middleware('auth');
	Route::get('antrian_laboratory', function() { return view('admission/self_checkin/antrian_laboratory'); } )->middleware('auth');
	Route::get('destination', function() { return view('admission/self_checkin/destination'); } )->middleware('auth');
	Route::get('menu_doktor', function() { return view('admission/self_checkin/menu_doktor'); } )->middleware('auth');
});

Route::prefix('nurse')->group(function () {
	Route::get('/', function () { return view('nurse/nurse_patient'); });
	
	Route::get('patient', function () { return view('nurse/nurse_patient'); })->middleware('auth');
	Route::get('anamnesa_umum', function () { return view('nurse/anamnesa_patient'); })->middleware('auth');
	
    Route::get('detail_patient', function () { return view('nurse/nurse_detail_patient'); })->middleware('auth')->name('nurse_detail_patient');
    
	
});

Route::prefix('doctor')->group(function () {
	Route::get('/', function () { return redirect('doctor/patient'); });
	
	Route::get('patient', function () { return view('doctor/patient'); })->middleware('auth');
	
	Route::get('calendar', function () { return view('doctor/calendar'); })->middleware('auth');
    
	Route::get('calendar', function () { return view('doctor/calendar'); })->middleware('auth');
	
    Route::get('form_request', function () { return view('doctor/form_request'); })->middleware('auth');

});

Route::prefix('cashier')->group(function () {
    Route::get('/', function() { return view('cashier/cashier'); })->middleware('auth')->name('cashier');
    Route::get('/cashier', function () { return view('cashier/cashier');  })->middleware('auth');
    Route::get('/selling_transaction', function () { return view('cashier/selling_transaction');  })->middleware('auth');
    Route::get('/exchange_labour_price', function () { return view('cashier/exchange_labour_price');  })->middleware('auth');
    Route::get('/table', function () { return view('cashier/table');  })->middleware('auth');
    Route::get('/cashier_transaction', function () { return view('cashier/cashier_transaction');  })->middleware('auth');
});

Route::prefix('admin')->group(function () {
	Route::get('/', function () { return redirect('admin/user'); });
    Route::resource('user', 'UserController', ['middleware' => 'auth']);
	Route::post('user/ajaxdt', 'UserController@ajaxdt')->middleware('auth');
	Route::post('user/editajax', 'UserController@editajax')->middleware('auth');
	
	Route::resource('role', 'RoleController', ['middleware' => 'auth']);
	Route::post('role/ajaxdt', 'RoleController@ajaxdt')->middleware('auth');
	Route::post('role/editajax', 'RoleController@editajax')->middleware('auth');
	
	Route::resource('doctor', 'DoctorController', ['middleware' => 'auth']);
	Route::post('doctor/ajaxdt', 'DoctorController@ajaxdt')->middleware('auth');
	Route::post('doctor/editajax', 'DoctorController@editajax')->middleware('auth');
	
	Route::get('place', 'ProvinceController@index', ['middleware' => 'auth'])->name('place');

	Route::resource('menu', 'MenuController', ['middleware' => 'auth']);
	Route::post('menu/ajaxdt','MenuController@ajaxdt')->middleware('auth');
	Route::post('menu/editajax','MenuController@ajaxdt')->middleware('auth');

	Route::resource('visit_code', 'VisitCodeController', ['middleware' => 'auth']);
	Route::post('visit_code/ajaxdt','VisitCodeController@ajaxdt')->middleware('auth');
	Route::post('visit_code/editajax','VisitCodeController@editajax')->middleware('auth');
    Route::post('visit_code/visitcode', 'VisitCodeController@storevisit')->middleware('auth')->name('visitcode');

    Route::resource('job_type', 'JobTypeController', ['middleware' => 'auth']);
    Route::post('job_type/ajaxdt','JobTypeController@ajaxdt')->middleware('auth');
    Route::post('job_type/editajax','JobTypeController@editajax')->middleware('auth');
    Route::post('job_type/jobtype', 'JobTypeController@storejob')->middleware('auth')->name('jobtype');

    Route::resource('id_type', 'IdTypeController', ['middleware' => 'auth']);
    Route::post('id_type/ajaxdt','IdTypeController@ajaxdt')->middleware('auth');
    Route::post('id_type/editajax','IdTypeController@editajax')->middleware('auth');
    Route::post('id_type/idtype', 'IdTypeController@storeid')->middleware('auth')->name('idtype');

    Route::resource('country', 'CountryController', ['middleware' => 'auth']);
    Route::post('country/ajaxdt','CountryController@ajaxdt')->middleware('auth');
    Route::post('country/editajax','CountryController@editajax')->middleware('auth');
    Route::post('country/country', 'CountryController@storeCountry')->middleware('auth')->name('country');

    Route::resource('province', 'ProvinceController', ['middleware' => 'auth']);
	Route::post('province/ajaxdt', 'ProvinceController@ajaxdt')->middleware('auth');
	Route::post('province/editajax', 'ProvinceController@editajax')->middleware('auth');

    Route::resource('city', 'CityController', ['middleware' => 'auth']); //
    Route::post('city/ajaxdt', 'CityController@ajaxdt')->middleware('auth');//untuk datatables
    Route::post('city/editajax', 'CityController@editajax')->middleware('auth'); //untuk
	
	Route::get('setting', function () { return view('admin/setting'); })->middleware('auth')->name('setting');
});

Route::prefix('cron')->group(function () {
	Route::get('city', 'CronController@city', ['middleware' => 'auth'])->name('cron_city');
	Route::get('province', 'CronController@province', ['middleware' => 'auth'])->name('cron_province');
	Route::get('backupdb', 'CronController@backupdb', ['middleware' => 'auth'])->name('backupdb');
});

Auth::routes();

app/City.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $table = "master_city";

    public function province(){
        return $this->belongsTo("App\Province"); //ambil id province dr tbl province
    }
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use App\City;
use App\Province;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Datatables;
use Hash;
use Illuminate\Validation\Rule;

class CityController extends Controller
{
    /**
     * Show a list of all of the application's province.
     *
     * @return Response
     */
    public function index(Request $request)
    {
        return view('admin/city/city', ['province' => Province::all()]);
    }

    public function ajaxdt()
    {
        $data = City::with('province')->get();
        return Datatables::of($data)->make(true);
    }

//    public function show($id)
//    {
//        return view('admin/city/city-edit', ['city' => City::findOrFail($id)]);
//    }
//
//    public function create()
//    {
//        return view('admin/city/city-create');
//    }
//
//    public function edit($id)
//    {
//        return view('admin/city/city-edit', ['city' => City::findOrFail($id)]);
//    }

    public function editajax(Request $req)
    {
        return response()->json([
            'status' => '200',
            'success' => true,
            'data' => City::findOrFail($req->id)
        ]);
    }

    public function destroy($id)
    {
        $del = City::find($id);
        $del->delete();
        return response()->json([
            'status' => '200',
            'success' => true
        ]);
    }

    public function store(Request $request)
    {
        $validate = \Validator::make($request->all(), [
            'name' => 'required|unique:master_city|max:255',
            'province' => 'required',
        ],
            $after_save = [
                'alert' => 'error',
                'title' => 'Failed!',
                'text-1' => 'Error exists,',
                'text-2' => 'please try again.'
            ]);

        if($validate->fails()){
            return response()->json([
                'code' => '500',
                'alert' => 'error',
                'title' => 'Failed!',
                'description' => $validate->messages(),
                'success' => false
            ]);
        }

        $data = new City;
        $data->name = $request->name;
        $data->province_id = $request->province;
        $data->created_by = Auth::id();
        $data->save();

        $after_save = [
            'alert' => 'success',
            'title' => 'Saved!',
            'text-1' => 'Add new city',
            'text-2' => 'success.'
        ];

        return response()->json([
            'status' => '200',
            'alert' => 'success',
            'title' => 'Sukses!',
            'description' => 'Create new city success.',
            'success' => true
        ]);
    }

    public function update(Request $request, $id)
    {
        $validate = \Validator::make($request->all(), [
            'name' => 'required|max:255',
//            'province_id' => ['required|',
//                Province::unique('master_doctor')->ignore($id)]
            ],

            $after_save = [
                'alert' => 'error',
                'title' => 'Failed!',
                'text-1' => 'Error exists,',
                'text-2' => 'please try again.'
            ]);

        if($validate->fails()){
            return response()->json([
                'code' => '500',
                'alert' => 'error',
                'title' => 'Failed!',
                'description' => $validate->messages(),
                'success' => false
            ]);
        }

        $data = City::find($id);
        $data->name = $request->name;
        $data->province_id = $request->province;
        $data->save();

        $after_save = [
            'alert' => 'success',
            'title' => 'Saved!',
            'text-1' => 'Update city data',
            'text-2' => 'success.'
        ];

        return response()->json([
            'status' => '200',
            'alert' => 'success',
            'title' => 'Sukses!',
            'description' => 'Update data city success.',
            'success' => true
        ]);
    }

}

resources/views/admin/city/city.blade.php
@extends('layouts.layout')
@section('content')
	<main class="mn-inner">
		<div class="col s12">
			<div>
				<div id="res">
					<div class="col s12">
						<div>
							<div id="regis" >
								<div class="card-content">
									<div class="row">
										<form class="col s12 m12 card-panel" method="post" id="reservation_form">
											<div class="row" style="margin-top: 20px;"></div>
											<div class="row">
												<label class="col lebel"><i class="material-icons prefix">account_circle</i></label>
												<input type="text" class="col s2" id="name" name="name" placeholder="Name City" style="margin-left: 20px;">
												<button style="margin-left: 5%" type="submit" class="waves-effect waves-light btn" href="#">Find</button>
												<a style="margin-left: 5%" class="waves-effect waves-light btn" href="#">Print</a>
												<a style="margin-left: 5%;" class="waves-effect waves-light btn modal-trigger" href="#newData">Add</a>
											</div>
										</form>
									</div>

									<div class="card-panel" id="data_reservation">
										<table id="data" class="display responsive-table datatable-example" cellspacing="0" width="100%">
											<thead>
												<tr>
													<th>No.</th>
													<th>City Name</th>
													<th>Province Name</th>
													<th>Actions</th>
												</tr>
											</thead>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		{{--Modals New--}}
		<div id="newData" class="modal modal-fixed-footer">
			<form action="{{ route('city.index') }}" method="post" id="newform">
			{{ csrf_field() }}
				<div class="modal-content">
					<h4 style="font-size: 20px;padding-left: 45%;">New City</h4><br>
					
					<div class="row">
						<label class="col label">City Name</label>
						<input type="text" name="name" placeholder="City Name" class="col s8">
					</div>
					<div class="row">
						<label class="col lebel">Province Name</label>
						<select class="form-control" id="province" name="province">
							@foreach($province as $item)
								<option value="{{$item->id}}"> {{$item->name}}</option>
							@endforeach
						</select>
					</div>
				</div>
				<div class="modal-footer">
					<button id="button_add" type="submit" class="modal-action modal-close waves-effect waves-blue btn-flat ">Submit</button>
					<a href="#!" class="modal-action modal-close waves-effect waves-blue btn-flat ">Cancel</a>
				</div>
			</form>
		</div>

		{{--Modals Details--}}
		<div id="dataDetails" class="modal  modal-fixed-footer">
			<form action="" method="post" id="edit">
				{{ method_field('PUT') }}
				{{ csrf_field() }}
				<div class="modal-content">
					<h4 style="font-size: 20px;padding-left: 45%;">Edit City</h4><br>
					
					<div class="row">
						<label class="col label">City Name</label>
						<input type="text" name="name" placeholder="City Name" class="col s8">
					</div>
					<div class="row">
						<label class="col lebel">Province Name</label>
						<div class="input-field col s8">
							<select class="browser-default" id="province" name="province">
								@foreach($province as $item)
									<option value="{{$item->id}}" > {{$item->name}}</option>
								@endforeach
							</select>
						</div>
					</div>

				</div>
				<div class="modal-footer">
					<button id="button_edit" type="submit" class="modal-action modal-close waves-effect waves-blue btn-flat ">Submit</button>
					<a href="#!" class="modal-action modal-close waves-effect waves-blue btn-flat ">Cancel</a>
				</div>
			</form>
		</div>

	</main>
@endsection

@section('js')
	<script>
		$(document).ready(function() {
			getdata();
			$('.dataTables_length select').addClass('browser-default');
		});
		//ini ajax untuk nampilin data
		function getdata(){
			$('#data').DataTable( {
                language: {
                    searchPlaceholder: 'Search records',
					sSearch: '',
                    sLengthMenu: 'Show _MENU_',
                    sLength: 'dataTables_length',
					oPaginate: {
						sFirst: '<i class="material-icons">chevron_left</i>',
						sPrevious: '<i class="material-icons">chevron_left</i>',
						sNext: '<i class="material-icons">chevron_right</i>',
						sLast: '<i class="material-icons">chevron_right</i>'
					}
				},
				"processing": true,
				"serverSide": true,
				"ajax":{
					"url": "/admin/city/ajaxdt",
					"dataType": "json",
					"type": "POST",
				},
                'order': [[ 0, 'desc' ]],
				"columns": [
					{
						"data": "id",
						render: function (data, type, row, meta) {
							return meta.row + meta.settings._iDisplayStart + 1;
						}
					},
					{ "data": "name" },
                    {
                        "mRender": function (data, type, row, meta) {
                            return row.province.name;
                        }
                    },
					{
						"mRender": function (data, type, row, meta) {
							return '<a class="btn-floating" onclick="detail(`' + row.id + '`)"><i class="material-icons">zoom_in</i></a><a id="' + row.id + '" style="margin-left: 5%;" class="btn-floating" onclick="del(`' + row.id + '`)"><i class="material-icons">delete</i></a>';
						}
					}
				],
			});
            $("div.toolbar").html('<a style="margin-left: 5%;" class="waves-effect waves-light btn modal-trigger" href="#newData">Add</a>');
		}
		//ini ajax detail
		function detail(id){
			$.ajax({
				type: 'POST',
				url: '/admin/city/editajax',
				data: {
					'id' : id,
				},
				async: false,
				dataType: 'json',
				success: function(data) {
					var isi = (data.data);
					$('#edit').attr('action', '/admin/city/' + isi.id);
					$('#edit input[name="name"]').val(isi.name);
					$('#edit option[value="' + isi.province_id +'"]').attr('selected', 'selected');
				}

			});
            $('#dataDetails').openModal();
        }
		
		function del(id) {
			swal({
				title: "Are you sure?",
				text: "Delete this city?",
				type: "warning",
				showCancelButton: true,
				confirmButtonColor: "#DD6B55",
				confirmButtonText: "Confirm",
				closeOnConfirm: true
			}, function(){
				event.preventDefault();
				$.ajax({
					type: "DELETE",
					url: "/admin/city/" + id,
					dataType:"json",  
					success: function(data){
						if(data.success == true){
							//location.reload(true);
							$('#data').DataTable().destroy();
							getdata();
						}
					}
				});
				return false;
			});
		}

        //Button add City
        $('#button_add').click(function(e) {
            e.preventDefault();
            $.ajax({
                url: '/admin/city',
                type: 'post',
                dataType: 'json',
                async: false,
                data: $('form#newform').serialize(),
                success: function(data) {
                    var desc = new Array();
                    if(data.status != 200){
                        $.each(data.description, function(i,d) { //i=index, d=nama array,description=objek json
                            desc.push(d[0]);
                        });
                        var descr = desc.join('\n'); // join = gabungin array ke text, \n = pemisahnya
                    } else {
                        var descr = data.description;
                        $('#data').DataTable().destroy();
                        getdata();
                        $(':input','#newform')
                            .not(':button, :submit, :reset, :hidden')
                            .val('');
                    }
                    alertPopup(data.title, descr, data.alert);
                },
                error: function(d) {
                    console.log('error');
                }
            });
        });

        //Button Submit edit city
        $('#button_edit').click(function(e) {
            e.preventDefault();
            $.ajax({
                url: $('#edit').attr('action'),
                type: 'post',
                dataType: 'json',
                async: false,
                data: $('form#edit').serialize(),
                success: function(data) {
                    var desc = new Array();
                    if(data.status != 200){
                        $.each(data.description, function(i,d) {
                            desc.push(d[0]);
                        });
                        var descr = desc.join('\n');
                    } else {
                        var descr = data.description;
                        $('#data').DataTable().destroy();
                        getdata();
                    }
                    alertPopup(data.title, descr, data.alert);
                },
                error: function(d) {
                    console.log('error');
                }
            });
        });

        function alertPopup(title, text, type){
            swal({ title: title,
                text: text,
                type: type,
                //showConfirmButton: false,
                //timer: 3000,
            })
        }

		@if (Session::has('after_save'))
			var t = "{{ Session::get('after_save.title') }}";
			var txt = "{{ Session::get('after_save.text-1') }} {{ Session::get('after_save.text-2') }}";
			var ty = "{{ Session::get('after_save.alert') }}";
        alertPopup(t, txt,ty);
		@endif
	</script>
@endsection