routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\User;
use App\Role;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Auth;

Route::get('/login', function () {
    return view('login');
});

Route::get('/', function () {
	$roles = explode(",", Auth::user()->roles);
	$role = Role::find($roles[0]);
	return redirect($role->url);
})->middleware('auth');

Route::get('/home', function () { return view('admission/registration'); })->middleware('auth');

Route::prefix('profile')->group(function () {
	Route::get('/', 'ProfileController@index')->middleware('auth')->name('profile');
	Route::get('edit', 'ProfileController@edit')->middleware('auth')->name('profile_edit');
	Route::post('update', 'ProfileController@update')->middleware('auth')->name('profile_update');
});

Route::prefix('admission')->group(function () {	
	Route::get('/', function () { return redirect('admission/registration'); });
	
    Route::resource('registration', 'RegistrationController', ['middleware' => 'auth']);

	Route::post('doctor_show_all', 'AdmissionController@doctorshowall');
	Route::post('doctor_list', 'AdmissionController@doctorlist');

    Route::post('reservation_ajax', 'AdmissionController@reservationajax')->middleware('auth');
    
	Route::resource('master_patient', 'PatientController', ['middleware' => 'auth']);
	Route::post('master_patient/ajaxdt', 'PatientController@ajaxdt')->middleware('auth')->name('master_patient_ajaxdt');
	Route::post('master_patient/search_by_name_dt', 'PatientController@searchbynamedt')->middleware('auth')->name('search_by_name_dt');
	
	Route::get('daily_patient', function () { return view('admission/daily-patient'); })->middleware('auth')->name('daily_patient');
	
	Route::get('doctor_schedule', 'DoctorRequestSessionController@index')->middleware('auth')->name('doctor_schedule');
	Route::post('doctor_schedule/request_session_leave', 'DoctorRequestSessionController@storeRequestSessionLeave')->middleware('auth')->name('request_session_leave');

	Route::get('doctor_late', 'DoctorLateController@index')->middleware('auth')->name('doctor_late');
	Route::post('doctor_late/request_late', 'DoctorLateController@storeRequestLate')->middleware('auth')->name('request_late');

	Route::get('doctor_leave', 'DoctorLeaveController@index')->middleware('auth')->name('doctor_leave');
	Route::post('doctor_leave/request_leave', 'DoctorLeaveController@storeRequestLeave')->middleware('auth')->name('request_leave');

	Route::get('program', function () { return view('admission/program'); })->middleware('auth')->name('program');
	
	Route::get('information', function () { return view('admission/information/index'); })->middleware('auth')->name('information');
	
	Route::post('doctor_search_by_code', 'AdmissionController@doctorsearchbycode')->middleware('auth')->name('doctor_search_by_code');
});

Route::prefix('self_checkin')->group(function () {
	Route::get('/', function() { return view('admission/self_checkin/booking'); } )->middleware('auth');
	Route::get('antrian_pharmacy', function() { return view('admission/self_checkin/antrian_pharmacy'); } )->middleware('auth');
	Route::get('antrian_laboratory', function() { return view('admission/self_checkin/antrian_laboratory'); } )->middleware('auth');
	Route::get('destination', function() { return view('admission/self_checkin/destination'); } )->middleware('auth');
	Route::get('menu_doktor', function() { return view('admission/self_checkin/menu_doktor'); } )->middleware('auth');
});

Route::prefix('nurse')->group(function () {
	Route::get('/', function () { return view('nurse/nurse_patient'); });
	
	Route::get('patient', function () { return view('nurse/nurse_patient'); })->middleware('auth');
	Route::get('anamnesa_umum', function () { return view('nurse/anamnesa_patient'); })->middleware('auth');
	
    Route::get('detail_patient', function () { return view('nurse/nurse_detail_patient'); })->middleware('auth')->name('nurse_detail_patient');
    
	
});

Route::prefix('doctor')->group(function () {
	Route::get('/', function () { return redirect('doctor/patient'); });
	
	Route::get('patient', function () { return view('doctor/patient'); })->middleware('auth');
	
	Route::get('calendar', function () { return view('doctor/calendar'); })->middleware('auth');
    
	Route::get('calendar', function () { return view('doctor/calendar'); })->middleware('auth');
	
    Route::get('form_request', function () { return view('doctor/form_request'); })->middleware('auth');

});

Route::prefix('cashier')->group(function () {
    Route::get('/', function() { return view('cashier/cashier'); })->middleware('auth')->name('cashier');
    Route::get('/cashier', function () { return view('cashier/cashier');  })->middleware('auth');
    Route::get('/selling_transaction', function () { return view('cashier/selling_transaction');  })->middleware('auth');
    Route::get('/exchange_labour_price', function () { return view('cashier/exchange_labour_price');  })->middleware('auth');
    Route::get('/table', function () { return view('cashier/table');  })->middleware('auth');
    Route::get('/cashier_transaction', function () { return view('cashier/cashier_transaction');  })->middleware('auth');
});

Route::prefix('admin')->group(function () {
	Route::get('/', function () { return redirect('admin/user'); });
    Route::resource('user', 'UserController', ['middleware' => 'auth']);
	Route::post('user/ajaxdt', 'UserController@ajaxdt')->middleware('auth');
	Route::post('user/editajax', 'UserController@editajax')->middleware('auth');
	
	Route::resource('role', 'RoleController', ['middleware' => 'auth']);
	Route::post('role/ajaxdt', 'RoleController@ajaxdt')->middleware('auth');
	Route::post('role/editajax', 'RoleController@editajax')->middleware('auth');
	
	Route::resource('doctor', 'DoctorController', ['middleware' => 'auth']);
	Route::post('doctor/ajaxdt', 'DoctorController@ajaxdt')->middleware('auth');
	Route::post('doctor/editajax', 'DoctorController@editajax')->middleware('auth');
	
	Route::get('place', 'ProvinceController@index', ['middleware' => 'auth'])->name('place');

	Route::resource('menu', 'MenuController', ['middleware' => 'auth']);
	Route::post('menu/ajaxdt','MenuController@ajaxdt')->middleware('auth');
	Route::post('menu/editajax','MenuController@ajaxdt')->middleware('auth');

	Route::resource('visit_code', 'VisitCodeController', ['middleware' => 'auth']);
	Route::post('visit_code/ajaxdt','VisitCodeController@ajaxdt')->middleware('auth');
	Route::post('visit_code/editajax','VisitCodeController@editajax')->middleware('auth');
    Route::post('visit_code/visitcode', 'VisitCodeController@storevisit')->middleware('auth')->name('visitcode');

    Route::resource('job_type', 'JobTypeController', ['middleware' => 'auth']);
    Route::post('job_type/ajaxdt','JobTypeController@ajaxdt')->middleware('auth');
    Route::post('job_type/editajax','JobTypeController@editajax')->middleware('auth');
    Route::post('job_type/jobtype', 'JobTypeController@storejob')->middleware('auth')->name('jobtype');

    Route::resource('id_type', 'IdTypeController', ['middleware' => 'auth']);
    Route::post('id_type/ajaxdt','IdTypeController@ajaxdt')->middleware('auth');
    Route::post('id_type/editajax','IdTypeController@editajax')->middleware('auth');
    Route::post('id_type/idtype', 'IdTypeController@storeid')->middleware('auth')->name('idtype');

    Route::resource('country', 'CountryController', ['middleware' => 'auth']);
    Route::post('country/ajaxdt','CountryController@ajaxdt')->middleware('auth');
    Route::post('country/editajax','CountryController@editajax')->middleware('auth');
    Route::post('country/country', 'CountryController@storeCountry')->middleware('auth')->name('country');

    Route::resource('province', 'ProvinceController', ['middleware' => 'auth']);
	Route::post('province/ajaxdt', 'ProvinceController@ajaxdt')->middleware('auth');
	Route::post('province/editajax', 'ProvinceController@editajax')->middleware('auth');

    Route::resource('city', 'CityController', ['middleware' => 'auth']); //
    Route::post('city/ajaxdt', 'CityController@ajaxdt')->middleware('auth');//untuk datatables
    Route::post('city/editajax', 'CityController@editajax')->middleware('auth'); //untuk
	
	Route::get('setting', function () { return view('admin/setting'); })->middleware('auth')->name('setting');
});

Route::prefix('cron')->group(function () {
	Route::get('city', 'CronController@city', ['middleware' => 'auth'])->name('cron_city');
	Route::get('province', 'CronController@province', ['middleware' => 'auth'])->name('cron_province');
	Route::get('backupdb', 'CronController@backupdb', ['middleware' => 'auth'])->name('backupdb');
});

Auth::routes();

app/Http/Controllers/AdmissionController.php
<?php

namespace App\Http\Controllers;

use App\Reservation;
use App\Patient;
use App\PatientTemporary;
use App\Visit;
use App\Doctor;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Datatables;
use Auth;

class AdmissionController extends Controller
{
    public function __construct()
	{
		$this->middleware('auth');
	}
	
	public function dataajax()
    {
        $data = Reservation::get();
        return Datatables::of($data)->make(true);
    }
	
	public function reservationdetail(Request $req)
	{
		$data = Reservation::with('patient')->find($req->id);
		
		if(count($data) > 0){
			return response()->json([
				'status' => '200',
				'alert' => 'success',
				'title' => 'Sukses!',
				'description' => 'Reservation data found.',
				'success' => true,
				'data' => $data
			]);
		
		} else {
			return response()->json([
				'status' => '300',
				'alert' => 'failed',
				'title' => 'Failed!',
				'description' => 'Reservation data not found.',
				'success' => false,
				'data' => null,
			]);
		}
	}
	
	
	public function reservationshowall(Request $req)
    {
        $validate = \Validator::make($req->all(), [
			'company_code' => 'required',
			'doctor_code' => 'required',
			'reservation_date' => 'required|date',
		]);
		
		if($validate->fails()){
			return response()->json([
				'code' => '500',
				'alert' => 'failed',
				'title' => 'Failed!',
				'description' => $validate->messages(),
				'success' => false
			]);
		}
		
		$reservation_date = $req->reservation_date;
		$hour_start = strtotime($reservation_date." 09:00");
		$hour_end = strtotime($reservation_date." 16:00");
		$duration = 30;
		$timeslots = array();
		
		while ($hour_start < $hour_end) {
		   $timeslots[] = date('H:i:s', $hour_start);
		   $hour_start = strtotime("+$duration minute", $hour_start);
		}
		
		$n = 0;
		foreach ( $timeslots as $slot ) {
		   $data[$n]['reservation_id'] = '';
		   $data[$n]['reservation_date'] = $reservation_date;
		   $data[$n]['session'] = $slot;
		   $data[$n]['morula_id'] = '';
		   $data[$n]['first_name'] = '';
		   $data[$n]['last_name'] = '';
		   $data[$n]['birth_date'] = '';
		   $data[$n]['sex'] = '';
		   $data[$n]['mobile'] = '';
		   $data[$n]['visit'] = '';
		   $data[$n]['doctor_code'] = '';
		   $data[$n]['description'] = '';
		   $data[$n]['operator'] = '';
		   $n++;
		}

		$reservation = Reservation::where('reservation_date', $reservation_date)->get();

		foreach ( $reservation as $reserv ) {
			$key = array_search($reserv->session, $timeslots);

			if(is_int($key)){
			    if(isset($reserv->morula_id))
			        $patient = Patient::find($reserv->morula_id);
			    else
                    $patient = PatientTemporary::find($reserv->temp_id);

			    if(count($patient) > 0){
                    $data[$key]['first_name'] = $patient->first_name;
                    $data[$key]['last_name'] = $patient->last_name;
                    $data[$key]['birth_date'] = $patient->birth_date;
                    $data[$key]['sex'] = $patient->sex;
                    $data[$key]['mobile'] = $patient->mobile;
                }

			    $visit = Visit::find($reserv->visit_code);
				$data[$key]['reservation_id'] = $reserv->id;
				$data[$key]['morula_id'] = $reserv->morula_id;
				$data[$key]['visit'] = $visit->name_visit;
				$data[$key]['doctor_code'] = $reserv->doctor_code;
				$data[$key]['description'] = $reserv->description;
				$data[$key]['operator'] = $reserv->created_by;
			}

		}
		
		return Datatables::of($data)->make(true);
		
    }

	public function reservationstore(Request $request)
	{
        $reservation = Reservation::where('reservation_date', $request->reservation_date)
            ->where('session', $request->session)
            ->first();

        if(count($reservation) > 0){
            return response()->json([
                'code' => '500',
                'alert' => 'failed',
                'title' => 'Gagal!',
                'description' => 'Reservation exists.',
                'success' => false
            ]);
        }

        $dataR = new Reservation;

		if(isset($request->morula_id)){
			
			$patient = Patient::where('id', $request->morula_id)->first();
			
			if(count($patient) == 0){
				return response()->json([
					'code' => '500',
					'alert' => 'failed',
					'title' => 'Gagal!',
					'description' => 'Patient not found',
					'success' => false
				]);
			}
			
			$validate = \Validator::make($request->all(), [
				'reservation_date' => 'required|date',
				'session' => 'required|date_format:H:i:s',
				'visit_code' => 'required|numeric',
				'morula_id' => 'required'
			]);
			
			if($validate->fails()){
				return response()->json([
					'code' => '500',
					'alert' => 'failed',
					'title' => 'Gagal!',
					'description' => $validate->messages(),
					'success' => false
				]);
			}

            $dataR->morula_id = $request->morula_id;
		
		} else {
			$validate = \Validator::make($request->all(), [
				'reservation_date' => 'required|date',
				'session' => 'required',
				'visit_code' => 'required|numeric',
				//master_patient
				'first_name' => 'required',
				'last_name' => 'required',
				'sex' => 'required',
				'init_doctor' => 'required|numeric',
				'birth_date' => 'required|date',
				'mobile' => 'required|numeric',
				'mobile_2' => 'required|numeric',
				'id_number' => 'required|unique:master_patient|unique:master_patient_temp|numeric',
				'id_type' => 'required',
			]);
			
			if($validate->fails()){
				return response()->json([
					'code' => '500',
					'alert' => 'failed',
					'title' => 'Gagal!',
					'description' => $validate->messages(),
					'success' => false
				]);
			}
			
			$data = new PatientTemporary;
			$data->first_name = $request->first_name;
			$data->last_name = $request->last_name;
			$data->sex = $request->sex;
			$data->init_doctor = $request->init_doctor;
			$data->birth_date = $request->birth_date;
			$data->mobile = $request->mobile;
			$data->mobile_2 = $request->mobile_2;
            $data->id_number = $request->id_number;
            $data->id_type = $request->id_type;
            $data->status = 1;
			$data->created_by = Auth::id();
			$data->save();

            $dataR->temp_id = $data->id;
		}

		$dataR->reservation_date = $request->reservation_date;
		$dataR->session = $request->session;
		$dataR->visit_code = $request->visit_code;
		$dataR->doctor_code = $request->doctor_code;
		$dataR->description = $request->description;
		$dataR->created_by = Auth::id();
		$dataR->save();
		
		return response()->json([
			'status' => '200',
			'alert' => 'success',
            'title' => 'Sukses!',
            'description' => 'Create new reservation success.',
			'success' => true
		]);
		
	}
	
	public function visitcodeshowall()
	{
		$data = Visit::get();
		
		if(count($data) > 0){
			return response()->json([
				'status' => '200',
				'alert' => 'success',
				'title' => 'Sukses!',
				'description' => 'Visit code data found.',
				'success' => true,
				'data' => $data
			]);
		
		} else {
			return response()->json([
				'status' => '300',
				'alert' => 'failed',
				'title' => 'Failed!',
				'description' => 'Visit code data not found.',
				'success' => false,
				'data' => null,
			]);
		}
	}
	
	public function doctorsearchbycode(Request $req)
	{
		$data = Doctor::where('doctor_code', $req->code)->first();
		
		if(count($data) > 0){
			return response()->json([
				'status' => '200',
				'alert' => 'success',
				'title' => 'Sukses!',
				'description' => 'Doctor data found.',
				'success' => true,
				'data' => $data->name
			]);
		
		} else {
			return response()->json([
				'status' => '300',
				'alert' => 'failed',
				'title' => 'Failed!',
				'description' => 'Doctor data not found.',
				'success' => false,
				'data' => null,
			]);
		}
	}

	public function doctorshowall()
	{
		$data = Doctor::get();
		
		if(count($data) > 0){
			return response()->json([
				'status' => '200',
				'alert' => 'success',
				'title' => 'Sukses!',
				'description' => 'Doctor data found.',
				'success' => true,
				'data' => $data
			]);
		
		} else {
			return response()->json([
				'status' => '300',
				'alert' => 'failed',
				'title' => 'Failed!',
				'description' => 'Doctor data not found.',
				'success' => false,
				'data' => null,
			]);
		}
	}
	
	public function doctorlist()
	{
		$data = Doctor::get();
		$data_doctor = [];
		foreach($data as $dt){
			$doctor['id'] = $dt->id;
			$doctor['text'] = ($dt->doctor_code == "" ? "" : $dt->doctor_code." - ").$dt->name;
			$data_doctor[] = $doctor;
		}
		
		if(count($data) > 0){
			return response()->json($data_doctor);
		
		} else {
			return response()->json(null);
		}
	}

	public function initpatient(Request $req)
    {

    }
	
}

resources/views/admission/patient/index.blade.php
@extends('layouts.layout')

@section('content')
<main class="mn-inner">
	<div class="col s12">
		<div>
			{{--Main Tab Master Patient--}}
			<div id="mp" class="tab-content" style="display:block">
				<div class="card-panel">
				{{--<a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>--}}
					<table id="masterPatient" class="display responsive-table datatable-example" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>No</th>
								<th>Morula ID</th>
								<th>First Name</th>
								<th>Last Name</th>
								<th>Place Birth</th>
								<th>Date Birth</th>
								<th>F/M</th>
								<th>Doctor</th>
								<th>Phone No And HP</th>
								<th>Actions</th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
		</div>
	</div>
    <!--/div-->

	{{--Modals--}}
    <div id="newPatient" class="modal  modal-fixed-footer">
        <div class="modal-content">
            <h4 style="font-size: 20px;padding-left: 45%;">New Patient</h4>
            <br>
            <form method="post" id="submit_newPatient">
            <div class="row">
                <label class="col lebel">Session</label>
                <input type="text" name="session" class="timepicker col s1">
                <i class="material-icons" style="padding-top: 10px;">access_time</i>
            </div>

            <div class="row">
                <label class="col lebel">First Name</label>
                <input type="text" name="first_name" class="col s8">
            </div>

            <div class="row">
                <label class="col lebel">Last Name</label>
                <input type="text" name="last_name" class="col s8">
            </div>


            <input type="hidden" name="init_doctor" value="1">
            <input type="hidden" name="id_number" value="12738213">
            <input type="hidden" name="id_type" value="1">
                <input type="hidden" name="reservation_date" value="2017-09-12">
                <input type="hidden" name="visit_code" value="1">


            <div class="row">
                <label class="col lebel">Sex</label>
                <select name="sex" class="col s2">
                    <option value="" disabled selected></option>
                    <option value="1">Male</option>
                    <option value="2">Female</option>
                </select>
            </div>

            <div class="row">
                <label class="col lebel">Date of Birth</label>
                <input type="text" class="datepicker col" name="birth_date" style="width: 100px;">
                <i class="material-icons" style="padding-top: 10px;">date_range</i>
            </div>

            <div class="row">
                <label class="col lebel">Mobile no 1</label>
                <input type="text" name="mobile" class="col s8">
            </div>

            <div class="row">
                <label class="col lebel">Mobile no 2</label>
                <input type="text" name="mobile_2" class="col s8">
            </div>

            {{--<div class="row">--}}
                {{--<label class="col lebel">Operator</label>--}}
                {{--<input type="text" name="operator" readonly class="col s8">--}}
            {{--</div>--}}

            <div class="row">
                <label class="col lebel">Description</label>
                <textarea class="materialize-textarea col s8" name="description" data-length="120"></textarea>
            </div>

        </div>
        <div class="modal-footer">
            <button type="submit" class="modal-action modal-close waves-effect waves-blue btn-flat ">Submit</button>
            <a href="#!" class="modal-action modal-close waves-effect waves-blue btn-flat ">Cencel</a>
        </div>
        </form>
    </div>
</main>
@endsection

@section('js')
<script>
	$(document).ready(function() {
		function pad (str, max) {
		  str = str.toString();
		  return str.length < max ? pad("0" + str, max) : str;
		}
		
	   $('#masterPatient').DataTable( {
			language: {
				searchPlaceholder: 'Search records',
				sSearch: '',
				sLengthMenu: 'Show _MENU_',
				sLength: 'dataTables_length',
				oPaginate: {
					sFirst: '<i class="material-icons">chevron_left</i>',
					sPrevious: '<i class="material-icons">chevron_left</i>',
					sNext: '<i class="material-icons">chevron_right</i>',
					sLast: '<i class="material-icons">chevron_right</i>'
				}
			},
			"processing": true,
			"serverSide": true,
			"ajax":{
				"url": "{{ route('master_patient_ajaxdt') }}",
				"dataType": "json",
				"type": "POST",
				"headers": {
					"X-CSRF-TOKEN": "{{ csrf_token() }}"
				}
			},
			"columns": [
				{
					"data": "id",
						render: function (data, type, row, meta) {
							return meta.row + meta.settings._iDisplayStart + 1;
						}
				},
				{
					"mRender": function (data, type, row) {
						return row.company_id + '-' + pad(row.id, 4);
					}
				},
				{ "data": "first_name" },
				{ "data": "last_name" },
				{ "data": "birth_place" },
				{ "data": "birth_date" },
				{ "data": "sex" },
				{ "data": "init_doctor" },
				{ "data": "phone" },
				{
					"mRender": function (data, type, row) {
						return '<a href=\"{{ route("master_patient.index") }}/' + row.id +'\" class="btn">Detail</a>';
					}
				}
			],
		});
		$('.dataTables_length select').addClass('browser-default');

	});	
</script>
@endsection