routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\User;
use App\Role;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Auth;

Route::get('/login', function () {
    return view('login');
});

Route::get('/', function () {
	$roles = explode(",", Auth::user()->roles);
	$role = Role::find($roles[0]);
	return redirect($role->url);
})->middleware('auth');

Route::get('/home', function () { return view('admission/registration'); })->middleware('auth');

Route::prefix('profile')->group(function () {
	Route::get('/', 'ProfileController@index')->middleware('auth')->name('profile');
	Route::get('edit', 'ProfileController@edit')->middleware('auth')->name('profile_edit');
	Route::post('update', 'ProfileController@update')->middleware('auth')->name('profile_update');
});

Route::prefix('admission')->group(function () {	
	Route::get('/', function () { return redirect('admission/registration'); });
	
    Route::resource('registration', 'RegistrationController', ['middleware' => 'auth']);

	Route::post('doctor_show_all', 'AdmissionController@doctorshowall');
	Route::post('doctor_list', 'AdmissionController@doctorlist');

    Route::post('reservation_ajax', 'AdmissionController@reservationajax')->middleware('auth');
    
	Route::resource('master_patient', 'PatientController', ['middleware' => 'auth']);
	Route::post('master_patient/ajaxdt', 'PatientController@ajaxdt')->middleware('auth')->name('master_patient_ajaxdt');
	Route::post('master_patient/search_by_name_dt', 'PatientController@searchbynamedt')->middleware('auth')->name('search_by_name_dt');
	
	Route::get('daily_patient', function () { return view('admission/daily-patient'); })->middleware('auth')->name('daily_patient');
	
	Route::get('doctor_schedule', 'DoctorRequestSessionController@index')->middleware('auth')->name('doctor_schedule');
	Route::post('doctor_schedule/request_session_leave', 'DoctorRequestSessionController@storeRequestSessionLeave')->middleware('auth')->name('request_session_leave');

	Route::get('doctor_late', 'DoctorLateController@index')->middleware('auth')->name('doctor_late');
	Route::post('doctor_late/request_late', 'DoctorLateController@storeRequestLate')->middleware('auth')->name('request_late');

	Route::get('doctor_leave', 'DoctorLeaveController@index')->middleware('auth')->name('doctor_leave');
	Route::post('doctor_leave/request_leave', 'DoctorLeaveController@storeRequestLeave')->middleware('auth')->name('request_leave');

	Route::get('program', function () { return view('admission/program'); })->middleware('auth')->name('program');
	
	Route::get('information', function () { return view('admission/information/index'); })->middleware('auth')->name('information');
	
	Route::post('doctor_search_by_code', 'AdmissionController@doctorsearchbycode')->middleware('auth')->name('doctor_search_by_code');
});

Route::prefix('self_checkin')->group(function () {
	Route::get('/', function() { return view('admission/self_checkin/booking'); } )->middleware('auth');
	Route::get('antrian_pharmacy', function() { return view('admission/self_checkin/antrian_pharmacy'); } )->middleware('auth');
	Route::get('antrian_laboratory', function() { return view('admission/self_checkin/antrian_laboratory'); } )->middleware('auth');
	Route::get('destination', function() { return view('admission/self_checkin/destination'); } )->middleware('auth');
	Route::get('menu_doktor', function() { return view('admission/self_checkin/menu_doktor'); } )->middleware('auth');
});

Route::prefix('nurse')->group(function () {
	Route::get('/', function () { return view('nurse/nurse_patient'); });
	
	Route::get('patient', function () { return view('nurse/nurse_patient'); })->middleware('auth');
	Route::get('anamnesa_umum', function () { return view('nurse/anamnesa_patient'); })->middleware('auth');
	
    Route::get('detail_patient', function () { return view('nurse/nurse_detail_patient'); })->middleware('auth')->name('nurse_detail_patient');
    
	
});

Route::prefix('doctor')->group(function () {
	Route::get('/', function () { return redirect('doctor/patient'); });
	
	Route::get('patient', function () { return view('doctor/patient'); })->middleware('auth');
	
	Route::get('calendar', function () { return view('doctor/calendar'); })->middleware('auth');
    
	Route::get('calendar', function () { return view('doctor/calendar'); })->middleware('auth');
	
    Route::get('form_request', function () { return view('doctor/form_request'); })->middleware('auth');

});

Route::prefix('cashier')->group(function () {
    Route::get('/', function() { return view('cashier/cashier'); })->middleware('auth')->name('cashier');
    Route::get('/cashier', function () { return view('cashier/cashier');  })->middleware('auth');
    Route::get('/selling_transaction', function () { return view('cashier/selling_transaction');  })->middleware('auth');
    Route::get('/exchange_labour_price', function () { return view('cashier/exchange_labour_price');  })->middleware('auth');
    Route::get('/table', function () { return view('cashier/table');  })->middleware('auth');
    Route::get('/cashier_transaction', function () { return view('cashier/cashier_transaction');  })->middleware('auth');
});

Route::prefix('admin')->group(function () {
	Route::get('/', function () { return redirect('admin/user'); });
    Route::resource('user', 'UserController', ['middleware' => 'auth']);
	Route::post('user/ajaxdt', 'UserController@ajaxdt')->middleware('auth');
	Route::post('user/editajax', 'UserController@editajax')->middleware('auth');
	
	Route::resource('role', 'RoleController', ['middleware' => 'auth']);
	Route::post('role/ajaxdt', 'RoleController@ajaxdt')->middleware('auth');
	Route::post('role/editajax', 'RoleController@editajax')->middleware('auth');
	
	Route::resource('doctor', 'DoctorController', ['middleware' => 'auth']);
	Route::post('doctor/ajaxdt', 'DoctorController@ajaxdt')->middleware('auth');
	Route::post('doctor/editajax', 'DoctorController@editajax')->middleware('auth');
	
	Route::get('place', 'ProvinceController@index', ['middleware' => 'auth'])->name('place');

	Route::resource('menu', 'MenuController', ['middleware' => 'auth']);
	Route::post('menu/ajaxdt','MenuController@ajaxdt')->middleware('auth');
	Route::post('menu/editajax','MenuController@ajaxdt')->middleware('auth');

	Route::resource('visit_code', 'VisitCodeController', ['middleware' => 'auth']);
	Route::post('visit_code/ajaxdt','VisitCodeController@ajaxdt')->middleware('auth');
	Route::post('visit_code/editajax','VisitCodeController@editajax')->middleware('auth');
    Route::post('visit_code/visitcode', 'VisitCodeController@storevisit')->middleware('auth')->name('visitcode');

    Route::resource('job_type', 'JobTypeController', ['middleware' => 'auth']);
    Route::post('job_type/ajaxdt','JobTypeController@ajaxdt')->middleware('auth');
    Route::post('job_type/editajax','JobTypeController@editajax')->middleware('auth');
    Route::post('job_type/jobtype', 'JobTypeController@storejob')->middleware('auth')->name('jobtype');

    Route::resource('id_type', 'IdTypeController', ['middleware' => 'auth']);
    Route::post('id_type/ajaxdt','IdTypeController@ajaxdt')->middleware('auth');
    Route::post('id_type/editajax','IdTypeController@editajax')->middleware('auth');
    Route::post('id_type/idtype', 'IdTypeController@storeid')->middleware('auth')->name('idtype');

    Route::resource('country', 'CountryController', ['middleware' => 'auth']);
    Route::post('country/ajaxdt','CountryController@ajaxdt')->middleware('auth');
    Route::post('country/editajax','CountryController@editajax')->middleware('auth');
    Route::post('country/country', 'CountryController@storeCountry')->middleware('auth')->name('country');

    Route::resource('province', 'ProvinceController', ['middleware' => 'auth']);
	Route::post('province/ajaxdt', 'ProvinceController@ajaxdt')->middleware('auth');
	Route::post('province/editajax', 'ProvinceController@editajax')->middleware('auth');

    Route::resource('city', 'CityController', ['middleware' => 'auth']); //
    Route::post('city/ajaxdt', 'CityController@ajaxdt')->middleware('auth');//untuk datatables
    Route::post('city/editajax', 'CityController@editajax')->middleware('auth'); //untuk
	
	Route::get('setting', function () { return view('admin/setting'); })->middleware('auth')->name('setting');
});

Route::prefix('cron')->group(function () {
	Route::get('city', 'CronController@city', ['middleware' => 'auth'])->name('cron_city');
	Route::get('province', 'CronController@province', ['middleware' => 'auth'])->name('cron_province');
	Route::get('backupdb', 'CronController@backupdb', ['middleware' => 'auth'])->name('backupdb');
});

Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'roles'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'api_token'
    ];
	
	//protected $table = 'users';

    public function roles()
    {
        return $this->belongsToMany('App\Role', 'user_role', 'user_id', 'role_id');
    }

    public function hasAnyRole($roles)
    {
        if(is_array($roles)){
            foreach ($roles as $role) {
                if($this->hasRole($role)){
                    return true;
                }
            }
        } else {
            if($this->hasRole($roles)){
                return true;
            }
        }
        return false;
    }

    public function hasRole($role)
    {
        if($this->roles()->where('name', $role)->first()){
            return true;
        }
        return false;
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\UserRole;
use App\Role;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Datatables;
use Hash;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    /**
     * Show a list of all of the application's users.
     *
     * @return Response
     */
	
	 
    public function index(Request $request)
    {
		return view('admin/user/index', ['roles' => Role::get()->sortByDesc("id"), 
									'max' => Role::orderBy('id', 'desc')->get(),
								]);
    }
	
	public function ajaxdt()
	{
		$data = User::where('id', '!=', Auth::id())
			->orWhereNull('id')->get();
		return Datatables::of($data)->make(true);
	}
	
	public function show($id)
    {
        return view('admin/user/edit', ['user' => User::findOrFail($id)]);
    }
	
	public function create()
    {
		$roles = Role::get()->sortByDesc("id");
		return view('admin/user/create', ['roles' => $roles, 'max' => Role::orderBy('id', 'desc')->get()]);
    }
	
	public function edit($id)
    {
        return view('admin/user/edit', ['user' => User::findOrFail($id)]);
    }
	
	public function editajax(Request $req)
    {
		return response()->json([
			'status' => '200',
			'success' => true,
			'data' => User::findOrFail($req->id)
		]);
    }
	
	public function destroy($id)
    {
		$del = User::find($id);
		
		$del->delete();
		
		return response()->json([
			'status' => '200',
			'success' => true
		]);
    }
	
	public function store(Request $request)
    {
		
		$validate = \Validator::make($request->all(), [
			'username' => 'required|unique:users|max:20',
			'password' => 'required',
			'name' => 'required|max:30',
			'email' => 'email|max:50',
			'phone' => 'numeric'
		],
		
		$after_save = [
			'alert' => 'error',
			'title' => 'Failed!',
			'text-1' => 'Error exists,',
			'text-2' => 'please try again.'
		]);
		
		if($validate->fails()){
            return redirect('admin/user/create')
				->withErrors($validate, 'add')
				->withInput()
				->with('after_save', $after_save);
        }
		
		$after_save = [
            'alert' => 'success',
            'title' => 'Saved!',
            'text-1' => 'Add new user',
            'text-2' => 'success.'
        ];
		
		$data = new User;
		$data->username = $request->username;
		$data->password = Hash::make($request->password);
		$data->name = $request->name;
		$data->email = $request->email;
		$data->phone = $request->phone;
		$data->description = $request->description;
		
		if(count($request->roles) > 0){
			$roles = implode(",", $request->roles);
			$data->roles = $roles;
		}
		
		$data->save();
		return redirect('admin/user')->with('after_save', $after_save);
    }
	
	public function storeajax(Request $request)
    {
		
		$validate = \Validator::make($request->all(), [
			'username' => 'required|unique:users|max:20',
			'password' => 'required',
			'name' => 'required|max:30',
			'email' => 'required|email|max:50',
			'phone' => 'numeric'
		], 
			$after_save = [
				'alert' => 'error',
				'title' => 'Failed!',
				'text-1' => 'Error exists,',
				'text-2' => 'please try again.'
		]);
		
		/*if($validate->fails()){
            return redirect('admin/user/create')
				->withErrors($validate, 'add')
				->withInput()
				->with('after_save', $after_save);
        }*/
		
		if($validate->fails()){
			return response()->json([
				'code' => '500',
				'alert' => 'failed',
				'title' => 'Gagal!',
				'description' => $validate->messages(),
				'success' => false
			]);
		}
		
		$after_save = [
            'alert' => 'success',
            'title' => 'Saved!',
            'text-1' => 'Add new user',
            'text-2' => 'success.'
        ];
		
		$data = new User;
		$data->username = $request->username;
		$data->password = Hash::make($request->password);
		$data->name = $request->name;
		$data->email = $request->email;
		$data->phone = $request->phone;
		$data->description = $request->description;
		
		if(count($request->roles) > 0){
			$roles = implode(",", $request->roles);
			$data->roles = $roles;
		}
		
		$data->save();
		//return redirect('admin/user')->with('after_save', $after_save);
		
		return response()->json([
			'status' => '200',
			'alert' => 'success',
            'title' => 'Sukses!',
            'description' => 'Create new reservation success.',
			'success' => true
		]);
    }
	
	public function update(Request $request, $id)
    {
		$validate = \Validator::make($request->all(), [
			'username' => [
				'required',
				'max:20',
				Rule::unique('users')->ignore($id),
			],
			'name' => 'required|max:30',
			'email' => 'email',
			'phone' => 'numeric'
		],
		
		$after_save = [
            'alert' => 'error',
			'title' => 'Failed!',
			'text-1' => 'Error exists,',
			'text-2' => 'please try again.'
		]);
		
		if($validate->fails()){
            return redirect("admin/user/$id/edit")
				->withErrors($validate, 'update')
				->withInput()
				->with('after_save', $after_save);
        }
		
		$data = User::find($id);
		$data->username = $request->username;
		$data->name = $request->name;
		$data->email = $request->email;
		$data->phone = $request->phone;
		$data->description = $request->description;
		
		if($request->password != '')
			$data->password = Hash::make($request->password);
		
		if(count($request->roles) > 0){
			$roles = implode(",", $request->roles);
			$data->roles = $roles;
		}
		
		$data->save();
		
		$after_save = [
            'alert' => 'success',
            'title' => 'Saved!',
            'text-1' => 'Update user data',
            'text-2' => 'success.'
        ];
		
		return redirect('admin/user')->with('after_save', $after_save);
    }
	
}

resources/views/admin/user/create.blade.php
@extends('layouts.layout-admin')
@section('content')
	<main class="mn-inner">
		<div class="col s12">
			<div>
				<div id="res">
					<div class="col s12">
						<div>
							<div id="regis" >
								<form action="{{ route('user.index') }}" class="col s12 m12 card-panel" method="post" id="user_form_add">
									<div class="card-content">
										<div class="card-panel" id="data_reservation">
											<div id="newPatient" class="">
												<form action="{{ route('user.index') }}" method="post" id="newuser">
												{{ csrf_field() }}
													<div class="modal-content">
														<h4 style="font-size: 20px;padding-left: 45%;">New User</h4><br>
														<div class="row">
															<label class="col lebel">Username</label>
															<input value="{{ old('username') }}" type="text" name="username" placeholder="Username" class="col s8">
															<span class="label label-danger red-text text-darken-1">{{ $errors->add->first('username') }}</span>
														</div>
														<div class="row">
															<label class="col lebel">Password</label>
															<input value="" type="password" name="password" placeholder="Password" class="col s8">
															<span class="label label-danger red-text text-darken-1">{{ $errors->add->first('password') }}</span>
														</div>
														<div class="row">
															<label class="col lebel">Full Name</label>
															<input value="{{ old('name') }}" type="text" name="name" placeholder="Full Name" class="col s8">
															<span class="label label-danger red-text text-darken-1">{{ $errors->add->first('name') }}</span>
														</div>
														<div class="row">
															<label class="col lebel">Email</label>
															<input value="{{ old('email') }}" type="email" name="email" placeholder="Email" class="col s8 validate">
															<span class="label label-danger red-text text-darken-1">{{ $errors->add->first('email') }}</span>
														</div>
														<div class="row">
															<label class="col lebel">Phone</label>
															<input value="{{ old('phone') }}" type="text" name="phone" placeholder="Phone" class="col s8">
															<span class="label label-danger red-text text-darken-1">{{ $errors->add->first('phone') }}</span>
														</div>
														<div class="row">
															<label class="col lebel">Description</label>
															<textarea class="materialize-textarea col s8" name="description" data-length="120">{{ old('description') }}</textarea>
														</div>
														<div class="row">
															@foreach($roles as $item)
																<label class="col lebel">{{ $item->id == $max[0]->id ? 'Roles' : '&nbsp;' }}</label>
																<p class="p-v-xs">
																	<input name="roles[]" type="checkbox" class="filled-in" id="role_{{ $item->id }}" value="{{ $item->id }}" />
																	<label for="role_{{ $item->id }}">{{ $item->name }}</label>
																</p>
															@endforeach
														</div>
													</div>
												</form>
											</div>
										</div>
										<div class="row">
											<div class="row" style="margin-top: 20px;">
											</div>
											<div class="row">
												<a style="margin-left: 5%;" class="waves-effect waves-light btn modal-trigger" href="{{ route('user.index') }}">Back</a>
												<button style="margin-left: 5%" type="submit" class="waves-effect waves-light btn" href="#">Save</button>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		{{--End Modals--}}
	</main>
@endsection

@section('js')
	<script>
		$(document).ready(function() {
			$('#user').DataTable( {
				language: {
					searchPlaceholder: 'Search records',
					sSearch: '',
					sLengthMenu: 'Show _MENU_',
					sLength: 'dataTables_length',
					oPaginate: {
						sFirst: '<i class="material-icons">chevron_left</i>',
						sPrevious: '<i class="material-icons">chevron_left</i>',
						sNext: '<i class="material-icons">chevron_right</i>',
						sLast: '<i class="material-icons">chevron_right</i>'
					}
				},
				"processing": true,
				"serverSide": true,
				"ajax":{
					"url": "user/ajaxdt",
					"dataType": "json",
					"type": "POST",
					/*"data": function(d) {
						var frm_data = theData;
						$.each(frm_data, function(key, val) {
							d[val.name] = val.value;
						});
					},*/
					/*"headers": {
						"authorization": "Bearer uEzFSH1CTVPj0mf2VLRmmtGVvNWUQwBR0u5QykJzFskllHEsEr7Z7dU806YcvyD23k2DgH5WLTYyU86TkepxeQRtY5gSINSuTuXX"
					}*/
				},
				"columns": [
					{
						"data": "id",
						render: function (data, type, row, meta) {
							return meta.row + meta.settings._iDisplayStart + 1;
						}
					},
					{ "data": "username" },
					{ "data": "name" },
					{ "data": "email" },
					{ "data": "phone" },
					{ "data": "description" },
					{
						"mRender": function () {
							return '<a href="/detail_patient" class="btn-floating"><i class="material-icons">zoom_in</i></a><a style="margin-left: 5%;" href="" class="btn-floating"><i class="material-icons">delete</i></a>';
						}
					}
				],
			});
			
			$('.dataTables_length select').addClass('browser-default');

		});
		
		@if (Session::has('after_save'))
            function alertSuccess(){
				swal({ title: "{{ Session::get('after_save.title') }}",
					text: "{{ Session::get('after_save.text-1') }} {{ Session::get('after_save.text-2') }}",
					type: "{{ Session::get('after_save.alert') }}",
					showConfirmButton: false,
					timer: 2000,
				})
			}
			alertSuccess();
        @endif
	</script>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.layout-admin')
@section('content')
	<main class="mn-inner">
		<div class="col s12">
			<div>
				<div id="res">
					<div class="col s12">
						<div>
							<div id="regis" >
								<form action='{{ url("admin/user/$user->id") }}' class="col s12 m12 card-panel" method="post" id="user_form_edit">
								{{ method_field('PUT') }}
								{{ csrf_field() }}
									<div class="card-content">
										<div class="card-panel" id="data_reservation">
											<div id="newPatient" class="">
												<div class="modal-content">
													<h4 style="font-size: 20px;padding-left: 45%;">Edit User</h4><br>
													<div class="row">
														<label class="col lebel">Username</label>
														<input value="{{ old('username', $user->username) }}" type="text" name="username" placeholder="Username" class="col s8">
														<span class="label label-danger red-text text-darken-1">{{ $errors->update->first('username') }}</span>
													</div>
													<div class="row">
														<label class="col lebel">Password</label>
														<input value="" type="password" name="password" placeholder="Kosongkan jika tidak ingin mengubah password" class="col s8">
														<span class="label label-danger red-text text-darken-1">{{ $errors->update->first('password') }}</span>
													</div>
													<div class="row">
														<label class="col lebel">Full Name</label>
														<input value="{{ old('name', $user->name) }}" type="text" name="name" placeholder="Full Name" class="col s8">
														<span class="label label-danger red-text text-darken-1">{{ $errors->update->first('name') }}</span>
													</div>
													<div class="row">
														<label class="col lebel">Email</label>
														<input value="{{ old('email', $user->email) }}" type="text" name="email" placeholder="Email" class="col s8">
														<span class="label label-danger red-text text-darken-1">{{ $errors->update->first('email') }}</span>
													</div>
													<div class="row">
														<label class="col lebel">Phone</label>
														<input value="{{ old('phone', $user->phone) }}" type="text" name="phone" placeholder="Phone" class="col s8">
														<span class="label label-danger red-text text-darken-1">{{ $errors->update->first('phone') }}</span>
													</div>
													<div class="row">
														<label class="col lebel">Description</label>
														<textarea class="materialize-textarea col s8" name="description" data-length="120">{{ old('description', $user->description) }}</textarea>
													</div>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="row" style="margin-top: 20px;">
											</div>
											<div class="row">
												<a style="margin-left: 5%;" class="waves-effect waves-light btn modal-trigger" href="{{ route('user.index') }}">Back</a>
												<button style="margin-left: 5%" type="submit" class="waves-effect waves-light btn" href="#">Save</button>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		{{--Modals--}}
		
	</main>
@endsection

@section('js')
	<script>
		@if (Session::has('after_save'))
            function alertSuccess(){
				swal({ title: "{{ Session::get('after_save.title') }}",
					text: "{{ Session::get('after_save.text-1') }} {{ Session::get('after_save.text-2') }}",
					type: "{{ Session::get('after_save.alert') }}",
					showConfirmButton: false,
					timer: 2000,
				})
			}
			alertSuccess();
        @endif
	</script>
@endsection